Changed healtchecks

diff --git a/.github/workflows/s_jewusiak_deployment_pre.yml b/.github/workflows/s_jewusiak_deployment_pre.yml
--- a/.github/workflows/s_jewusiak_deployment_pre.yml
+++ b/.github/workflows/s_jewusiak_deployment_pre.yml
@@ -149,7 +149,7 @@ jobs:
       - name: Create Network
         run: 'ssh github_uploads@s.jewusiak.pl "docker network inspect ${{ env.APP_NAME }}${{ env.ENV_SUFFIX }}_net >/dev/null 2>&1 || docker network create --driver bridge ${{ env.APP_NAME }}${{ env.ENV_SUFFIX }}_net"'
 
-  deploy:
+  stop_old_apps:
     needs: [ elasticsearch_build, postgres_build, build_app, test_app, environment_setup ]
     permissions:
       contents: 'read'
@@ -173,14 +173,90 @@ jobs:
       - name: Stop old elasticsearch
         run: 'ssh github_uploads@s.jewusiak.pl "docker stop ${{ env.ELASTICSEARCH_NAME }}${{ env.ENV_SUFFIX }} || true"'
 
+
+  deploy_postgres:
+    needs: [ stop_old_apps ]
+    permissions:
+      contents: 'read'
+      id-token: 'write'
+
+    runs-on: ubuntu-latest
+    steps:
+      - name: Set up SSH keys
+        run: |
+          mkdir -p ~/.ssh
+          echo "${{ secrets.S_JEWUSIAK_SSH_KEY }}" > ~/.ssh/id_ed25519
+          chmod 600 ~/.ssh/id_ed25519
+          ssh-keyscan s.jewusiak.pl >> ~/.ssh/known_hosts
+
       - name: Run new postgres
         run: 'ssh github_uploads@s.jewusiak.pl "docker run --rm -d --name ${{ env.POSTGRES_NAME }}${{ env.ENV_SUFFIX }} --net=${{ env.APP_NAME }}${{ env.ENV_SUFFIX }}_net -e \"POSTGRES_DB=luncher_core_pre\" -e \"POSTGRES_USER=luncher_core_pre_apiuser\" -e \"POSTGRES_PASSWORD=EHa56TpJXo#qog\" ${{ env.POSTGRES_NAME }}${{ env.ENV_SUFFIX }}:${{ env.VERSION }}"'
+
+      - name: Wait for postgres to start
+        run: |
+          while [ "`docker inspect -f {{.State.Health.Status}} ${{ env.POSTGRES_NAME }}${{ env.ENV_SUFFIX }}`"=="starting" ]; do
+            sleep 0.1;
+          done;
+          if [[ "`docker inspect -f {{.State.Health.Status}} ${{ env.POSTGRES_NAME }}${{ env.ENV_SUFFIX }}`"!="healthy" ]]; then
+            echo "Postgres failed to start"
+            exit 1
+          fi
+
+  deploy_elasticsearch:
+    needs: [ stop_old_apps ]
+    permissions:
+      contents: 'read'
+      id-token: 'write'
+
+    runs-on: ubuntu-latest
+    steps:
+      - name: Set up SSH keys
+        run: |
+          mkdir -p ~/.ssh
+          echo "${{ secrets.S_JEWUSIAK_SSH_KEY }}" > ~/.ssh/id_ed25519
+          chmod 600 ~/.ssh/id_ed25519
+          ssh-keyscan s.jewusiak.pl >> ~/.ssh/known_hosts
 
       - name: Run new elasticsearch
         run: 'ssh github_uploads@s.jewusiak.pl "docker run --rm -d --name ${{ env.ELASTICSEARCH_NAME }}${{ env.ENV_SUFFIX }} --net=${{ env.APP_NAME }}${{ env.ENV_SUFFIX }}_net -e \"discovery.type=single-node\" -e \"xpack.security.enabled=false\" ${{ env.ELASTICSEARCH_NAME }}${{ env.ENV_SUFFIX }}:${{ env.VERSION }}"'
 
+      - name: Wait for elasticsearch to start
+        run: |
+          while [ "`docker inspect -f {{.State.Health.Status}} ${{ env.ELASTICSEARCH_NAME }}${{ env.ENV_SUFFIX }}`"=="starting" ]; do
+            sleep 0.1;
+          done;
+          if [[ "`docker inspect -f {{.State.Health.Status}} ${{ env.ELASTICSEARCH_NAME }}${{ env.ENV_SUFFIX }}`"!="healthy" ]]; then
+            echo "Elasticsearch failed to start"
+            exit 1
+          fi
+
+  deploy_main_app:
+    needs: [ deploy_helper_services ]
+    permissions:
+      contents: 'read'
+      id-token: 'write'
+
+    runs-on: ubuntu-latest
+    steps:
+      - name: Set up SSH keys
+        run: |
+          mkdir -p ~/.ssh
+          echo "${{ secrets.S_JEWUSIAK_SSH_KEY }}" > ~/.ssh/id_ed25519
+          chmod 600 ~/.ssh/id_ed25519
+          ssh-keyscan s.jewusiak.pl >> ~/.ssh/known_hosts
+
       - name: Run Docker application
         run: 'ssh github_uploads@s.jewusiak.pl "docker run --rm -d --name ${{ env.APP_NAME }}${{ env.ENV_SUFFIX }} -p 8080:8080 --net=${{ env.APP_NAME }}${{ env.ENV_SUFFIX }}_net ${{ env.APP_NAME }}${{ env.ENV_SUFFIX }}:${{ env.VERSION }}"'
+
+      - name: Wait for application to start
+        run: |
+          while [ "`docker inspect -f {{.State.Health.Status}} ${{ env.APP_NAME }}${{ env.ENV_SUFFIX }}`"=="starting" ]; do
+            sleep 0.1;
+          done;
+          if [[ "`docker inspect -f {{.State.Health.Status}} ${{ env.APP_NAME }}${{ env.ENV_SUFFIX }}`"!="healthy" ]]; then
+            echo "luncher_core failed to start"
+            exit 1
+          fi
 
 #  cleanup:
 #    needs: [ push ]
